spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVE}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false

  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}


logging:
  level:
    root: ${LOGGING_ROOT_LOG_LEVEL:INFO}
    '[com.demo.tasktracker]': INFO
