# Main SpringBoot application configuration
# Shared by all environments
spring:
  application:
    name: task-tracker-api-h2

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs 

