spring:
  application:
    name: task-tracker-api-h2

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs  

# Logging configuration
logging:
  level:
    root: INFO
    '[com.demo.tasktracker]': DEBUG
    '[org.springframework.web]': INFO
    '[org.hibernate.sql]': DEBUG